name: window_utils
description: A flutter plugin for managing window decoration.
version: 1.0.2
authors:
  - Rhodes Davis Jr. <rody.davis.jr@gmail.com>
  - Rive <info@rive.app>
homepage: https://github.com/rive-app/window-utils
environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: WindowUtils
      windows:
        pluginClass: WindowUtils

dependencies:
  flutter:
    sdk: flutter
