// ignore_for_file: directives_ordering
/// This file is autogenerated and should not be committed to source control

import '../../test_driver/route_test.dart' as test_driver_route;

void main(List<String> args) {
  test_driver_route.main(args);
}
