// ignore_for_file: directives_ordering
/// This file is autogenerated and should not be committed to source control

import 'main_lib_test.dart' as main_lib;
import 'preparing_tests/commands_test.dart' as preparing_tests_commands;
import 'preparing_tests/testing_test.dart' as preparing_tests_testing;
import 'test_generator/test_generator_test.dart' as test_generator_test_generator;
import 'test_generator/test_merger_test.dart' as test_generator_test_merger;
import 'update/version_test.dart' as update_version;
import 'utils/enum_test.dart' as utils_enum;

void main() {
  main_lib.main();
  preparing_tests_commands.main();
  preparing_tests_testing.main();
  test_generator_test_generator.main();
  test_generator_test_merger.main();
  update_version.main();
  utils_enum.main();
}
