# Check https://dart-lang.github.io/linter/lints/ for lint rules documentation
# Update from http://dart-lang.github.io/linter/lints/options/options.html

analyzer:
  enable-experiment:
    - non-nullable
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
  language:
    strict-inference: true
    strict-raw-types: true