name: cli_util
version: 0.2.0
author: Dart Team <misc@dartlang.org>
description: A library to help in building Dart command-line apps.
homepage: https://github.com/dart-lang/cli_util

environment:
  sdk: '>=2.10.0 <3.0.0'
